CREATE SEQUENCE "SEQ_USUARIO" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_ACESSO_UNIFI" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_REDIRECIONAMENTO" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;